format = """
$character\
$directory\
[](fg:mauve bg:peach)\
$git_branch\
$git_status\
$git_metrics\
[](fg:peach bg:lavender)\
[\
$c\
$cmake\
$container\
$dart\
$deno\
$dotnet\
$golang\
$java\
$kotlin\
$kubernetes\
$lua\
$nodejs\
$php\
$python\
$rust\
](fg: #000000 bg:mauve)\
[](fg:lavender bg:flamingo)\
[\
$cmd_duration\
$git_commit\
$git_state\
$docker_context\
](fg:#ffffff bg:flamingo)\
[ ](fg:flamingo)
"""
# Set 'foo' as custom color palette
palette = 'catppuccin'

# Define custom colors
[palettes.catppuccin]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[git_commit]
style = "fg:text bg:flamingo"
format = '[ #$hash $tag]($style)'

[git_state]
style = "fg:text bg:flamingo"
format = '[\[$state $progress_current/$progress_total\]]($style)'

[git_branch]
style = "fg:mantle bg:peach"
format = "[ $symbol$branch(:$remote_branch)]($style)"

[git_status]
style = "fg:mantle bg:peach"
format = '[ $all_status$ahead_behind ]($style)'

[directory]
style = "fg:mantle bg:blue "
format = "[ $path ]($style)"
truncate_to_repo = false

# Replace the "❯" und "x" symbol in the prompt with vim mode
[character]
success_symbol = "[](green)[ ](bold fg:mantle bg:green)[](bg:blue fg:green)"
error_symbol = "[](red)[ ](bold fg:mantle bg:red)[](bg:blue fg:red)"
vimcmd_symbol = "[](lavender)[ ](bold fg:mantle bg:lavender)[](bg:blue fg:lavender)"
format = "$symbol"

[cmd_duration]
style = "fg:blue bg:flamingo"
format = " ﮫ [$duration]($style) "

[docker_context]
style = "fg:blue bg:flamingo"
format = " [$symbol$context]($style) "

[java]
style = "fg:mantle bg:pink"

[kubernetes]
style = "fg:mantle bg:pink"

[c]
style = "fg:mantle bg:pink"

[cmake]
style = "fg:mantle bg:pink"
format = "[ $symbol]($style)"

[container]
style = "fg:mantle bg:pink"

[dart]
style = "fg:mantle bg:pink"
format = "[ $symbol]($style)"

[deno]
style = "fg:mantle bg:pink"
format = "[ $symbol]($style)"

[dotnet]
style = "fg:mantle bg:pink"
format = "[ $symbol(🎯 $tfm )]($style)"

[golang]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'

[kotlin]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'

[lua]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'

[nodejs]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'
not_capable_style = "fg:red bg:pink"

[php]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'

[python]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'

[rust]
style = "fg:mantle bg:pink"
format = '[ $symbol]($style)'
